disp("Trapezio")
disp("h=1/2")
[res,error]=trapezios(0,1,"functrapezios",1/2)
disp("h=1/4")
[res,error]=trapezios(0,1,"functrapezios",1/4)
disp("h=1/8")
[res,error]=trapezios(0,1,"functrapezios",1/8)
disp("h=1/16")
[res,error]=trapezios(0,1,"functrapezios",1/16)

disp("Simpson")
disp("h=1/2")
[res,error]=simpson(0,1,"functrapezios",1/2)
disp("h=1/4")
[res,error]=simpson(0,1,"functrapezios",1/4)
disp("h=1/8")
[res,error]=simpson(0,1,"functrapezios",1/8)
disp("h=1/16")
[res,error]=simpson(0,1,"functrapezios",1/16)

disp("Ponto Medio")
disp("h=1/2")
[res,error,absoluto]=pontomedio(0,1,"functrapezios",1/2)
disp("h=1/4")
[res,error,absoluto]=pontomedio(0,1,"functrapezios",1/4)
disp("h=1/8")
[res,error,absoluto]=pontomedio(0,1,"functrapezios",1/8)
disp("h=1/16")
[res,error,absoluto]=pontomedio(0,1,"functrapezios",1/16)